POST http://localhost:3000/api/product HTTP/1.1
content-type: application/json

{
    "name": "Pinturas",
    "price": 340
}

###

PUT http://localhost:3000/api/product/1 HTTP/1.1
content-type: application/json

{
    "name": "UnCOEETE",
    "price": 100
}
###

PATCH  http://localhost:3000/api/product/1 HTTP/1.1
content-type: application/json

{
    "name": "una computadora"
}
###

DELETE   http://localhost:3000/api/product/3 HTTP/1.1
content-type: application/json


### 
POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json

{
  "name": "Test User",
  "email": "test@test.com",
  "password": "123456"
}
### 
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
  "email": "test@test.com",
  "password": "wrong passworkd"
}