POST http://localhost:3000/api/products HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhZG1pbkB0ZXN0LmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4MDkzODUzNCwiZXhwIjoxNzgxMDI0OTM0fQ.4uYSPbBo80hZ-CBMZDpQ52GVi7r7LBmWMKzZbam61X4

{
  "name": "Gaming Chair",
  "price": 250,
  "category_id": 3
}

###

PUT http://localhost:3000/api/product/1 HTTP/1.1
content-type: application/json

{
    "name": "UnCOEETE",
    "price": 100
}
###

PATCH  http://localhost:3000/api/product/1 HTTP/1.1
content-type: application/json

{
    "name": "una computadora"
}
###

DELETE   http://localhost:3000/api/product/3 HTTP/1.1
content-type: application/json


### 
POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json

{
  "name": "Admin User",
  "email": "admin@test.com",
  "password": "123456"
}
### 
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
   "email": "admin@test.com",
  "password": "123456"
}